services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    2biased.conato.developmentserser.serve:
        class: TwoBiased\ContaoDevelopmentServerBundle\Command\ServeCommand
        arguments:
            - '%contao.web_dir%'
